print("=======================")
print("loading from test.entry")
print("loading from test.entry")
print("loading from test.entry")
print("loading from test.entry")
print("loading from test.entry")
print("loading from test.entry")
print("loading from test.entry")
print("loading from test.entry")
print("loading from test.entry")
print("loading from test.entry")
print("=======================")
ModLoader.SetupFileHook("lua/HiveVision.lua", "lua/UWEExtension/HiveVision.lua", "post")
ModLoader.SetupFileHook("lua/HiveVisionMixin.lua", "lua/UWEExtension/HiveVisionMixin.lua", "post")